dist: bionic
language: haskell
ghc: 8.4.1
env:
  - LUA=5.3 LUAROCKS=3.0

before_install:
  - pip install --user hererocks
  - hererocks env --lua $LUA --luarocks $LUAROCKS
  - source env/bin/activate
  - luarocks install busted

install:
  - luarocks make rockspec/digestif-scm-1.rockspec

script:
  - busted
  - cabal install --disable-optimization hspec lsp-test
  - runhaskell spec/test-lsp.hs
